version: '2'
services:
  tasks-db:
    image: mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: tasks
      MYSQL_HOST: tasks-db
  tasks-ms:
    image: dafrodriguezro/2b_example
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3003 -b '0.0.0.0'"
    ports:
      - "3003:3003"
    environment:
        PORT: '3003'
    depends_on:
      - tasks-db
